// =============================================================================
// app_localizations.dart - 다국어 지원 및 통화 포맷
// =============================================================================
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:intl/intl.dart';
import 'providers/settings_provider.dart';

class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'ko': {
      'appTitle': '가계부',
      'cancel': '취소',
      'save': '저장',
      'add': '추가',
      'delete': '삭제',
      'confirm': '확인',
      'deleteConfirm': '삭제 확인',
      'edit': '수정',

      'budgetTab': '예산',
      'historyTab': '내역',
      'statsTab': '통계',
      'settingsTab': '설정',

      'budget': '예산',
      'used': '사용',
      'remaining': '남음',
      'ratio': '비율',
      'total': '합계',
      'difference': '차이',
      'changeRate': '증감률',
      'budgetName': '예산명',
      'budgetNameHint': '예: 식비, 교통비',
      'amount': '금액',
      'usedAmount': '사용금액',
      'addBudget': '예산 추가',
      'editBudget': '예산 수정',
      'addBudgetPlease': '예산을 추가해주세요',
      'applyMonthly': '매달 적용',
      'applyMonthlyDesc': '이후 모든 달에 자동 적용',
      'numberOnlyError': '숫자만 입력 가능합니다',

      'subBudget': '세부예산',
      'subBudgetName': '세부예산명',
      'subBudgetNameHint': '예: 점심, 저녁',
      'addSubBudget': '세부예산 추가',
      'editSubBudget': '세부예산 수정',
      'addSubBudgetPlease': '세부예산을 추가해주세요',
      'item': '항목',

      'expense': '지출',
      'expenseHistory': '지출 내역',
      'addExpense': '지출 추가',
      'editExpense': '지출 수정',
      'noExpense': '지출 내역이 없습니다',
      'memo': '내용',
      'memoHint': '예: 점심 김밥',
      'date': '날짜',
      'subBudgetOptional': '세부예산 (선택)',
      'notSelected': '선택 안함',

      'budgetAllocation': '예산 배분',
      'actualUsage': '실제 사용',
      'subBudgetAnalysis': '세부예산별 분석',
      'selectBudget': '예산을 선택하세요',
      'noBudget': '예산이 없습니다',
      'noSubBudget': '세부예산이 없습니다',
      'subBudgetUsage': '세부예산 사용 현황',
      'addBudgetFirst': '예산을 먼저 추가해주세요',

      'settings': '설정',
      'basicSettings': '기본 설정',
      'currency': '통화 단위',
      'selectCurrency': '통화 단위 선택',
      'startDayOfWeek': '시작 요일',
      'selectStartDay': '시작 요일 선택',
      'monthStartDay': '월 시작일',
      'selectMonthStartDay': '월 시작일 선택',
      'monthStartDayDesc': '급여일이나 원하는 날짜를 선택하세요',
      'language': '언어',
      'selectLanguage': '언어 선택',

      'notificationSettings': '알림 설정',
      'dailyReminder': '지출 입력 알림',
      'off': '꺼짐',
      'budgetAlert': '예산 초과 알림',
      'budgetAlertThreshold': '예산 알림 기준',

      'displaySettings': '화면/테마',
      'darkMode': '다크 모드',
      'selectThemeMode': '테마 모드 선택',
      'systemSetting': '시스템 설정',
      'lightMode': '라이트 모드',
      'darkModeOption': '다크 모드',
      'fontSize': '글꼴 크기',
      'selectFontSize': '글꼴 크기 선택',
      'fontSmall': '작게',
      'fontNormal': '보통',
      'fontLarge': '크게',
      'fontExtraLarge': '매우 크게',
      'colorTheme': '색상 테마',
      'selectColorTheme': '색상 테마 선택',

      'others': '기타',
      'appInfo': '앱 정보',
      'version': '버전',
      'help': '도움말',
      'appDesc': '간단하고 직관적인 가계부 앱입니다.',

      'helpBudgetTab': '예산 탭',
      'helpBudgetDesc': '• + 버튼으로 예산 추가\n• 예산 터치로 상세 화면 이동\n• 길게 눌러 수정/삭제',
      'helpSubBudget': '세부예산',
      'helpSubBudgetDesc': '• 예산 내 세부 항목 관리\n• 각 세부예산별 지출 추적',
      'helpStatsTab': '통계 탭',
      'helpStatsDesc': '• 예산별 사용 현황 파이 차트\n• 차트 터치로 상세 정보 확인',
      'helpTip': '팁',
      'helpTipDesc': '• "매달 적용" 체크 시 다음 달에 자동 복사',

      'monday': '월요일',
      'tuesday': '화요일',
      'wednesday': '수요일',
      'thursday': '목요일',
      'friday': '금요일',
      'saturday': '토요일',
      'sunday': '일요일',

      'indigo': '인디고',
      'green': '그린',
      'blue': '블루',
      'red': '레드',
      'orange': '오렌지',
      'purple': '퍼플',
      'pink': '핑크',
      'teal': '틸',

      'dataManagement': '데이터 관리',
      'exportExcel': '엑셀로 내보내기',
      'exportExcelDesc': '현재 월 데이터를 엑셀 파일로 저장',
      'exportSuccess': '내보내기 완료',
      'exportFailed': '내보내기 실패',
      'exporting': '내보내는 중...',

      'aiAnalysis': 'AI 분석하기',
      'geminiApiKey': 'Gemini API 키',
      'enterApiKey': 'API 키를 입력하세요',
      'selectPeriod': '분석 기간 선택',
      'requestAnalysis': '분석 요청하기',
      'analyzing': '분석 중...',
      'analysisResult': 'AI 분석 결과',
      'error': '오류',
      'summary': '요약',
      'insights': '핵심 인사이트',
      'warnings': '주의사항',
      'suggestions': '개선 제안',
      'spendingPlan': '지출 계획',  // #13
      'spendingPattern': '소비 패턴',
      'mainCategory': '주요 지출 항목',
      'spendingTrend': '지출 트렌드',
      'savingPotential': '절약 가능 금액',
      'riskLevel': '위험 수준',
      'trendIncreasing': '증가 추세',
      'trendDecreasing': '감소 추세',
      'trendStable': '안정적',
      'riskLow': '낮음',
      'riskMedium': '보통',
      'riskHigh': '높음',
      'duplicate': '복제',
      'duplicated': '복제되었습니다',
      'cancelAnalysis': '분석 취소',
      'analysisInProgress': 'AI 분석 진행 중',
      'analysisCancelled': '분석이 취소되었습니다',
      'analysisComplete': 'AI 분석 완료',
      'viewResult': '결과 보기',
      'viewAnalysisResult': '분석 결과 확인하기',
      'analysisPeriod': '분석 기간',
      'analyzedAt': '분석 시점',
      'analysisHistory': '분석 이력',
      'noAnalysisHistory': '분석 이력이 없습니다',
      'clearHistoryConfirm': '모든 분석 이력을 삭제하시겠습니까?',
      'clearAll': '전체 삭제',
      'close': '닫기',
      'importExcel': '엑셀에서 불러오기',
      'importExcelDesc': '엑셀 파일에서 데이터 가져오기',
      'importConfirm': '불러오기 확인',
      'importSummary': '다음 데이터를 불러옵니다:',
      'targetMonth': '대상 월',
      'importing': '불러오는 중...',
      'importSuccess': '불러오기 완료',
      'importFailed': '불러오기 실패',
      'noDataToImport': '불러올 데이터가 없습니다',
      'items': '개 항목',
      'selectTone': '응답 스타일 선택',
      'responseTone': '응답 스타일',
      'toneGentle': '온화한',
      'tonePraise': '칭찬',
      'toneFactual': '팩트폭력',
      'toneCoach': '코치',
      'toneHumorous': '유머러스',
      'filter': '필터',
      'searchHint': '메모, 예산명 검색',
      'countUnit': '건',
      'sortDateDesc': '최신순',
      'sortDateAsc': '오래된순',
      'sortAmountDesc': '금액 높은순',
      'sortAmountAsc': '금액 낮은순',
      'periodFilter': '기간',
      'startDate': '시작일',
      'endDate': '종료일',
      'budgetFilter': '예산',
      'subBudgetFilter': '세부예산',
      'allBudgets': '전체 예산',
      'allSubBudgets': '전체 세부예산',
      'resetFilter': '필터 초기화',
      'noExpenseFound': '지출 내역이 없습니다',
      'deleteExpenseConfirm': '이 지출을 삭제하시겠습니까?',
      'recurringExpense': '반복 지출',
      'recurringExpenseDesc': '정기 지출 자동 등록 관리',
      'noRecurringExpense': '등록된 반복 지출이 없습니다',
      'addRecurringExpense': '반복 지출 추가',
      'editRecurringExpense': '반복 지출 수정',
      'deleteRecurringConfirm': '이 반복 지출을 삭제하시겠습니까?',
      'repeatCycle': '반복 주기',
      'monthly': '매월',
      'weekly': '매주',
      'dayOfMonth': '일자',
      'dayOfWeek': '요일',
      'dayUnit': '일',
      'everyMonth': '매월',
      'everyWeek': '매주',
      'monShort': '월',
      'tueShort': '화',
      'wedShort': '수',
      'thuShort': '목',
      'friShort': '금',
      'satShort': '토',
      'sunShort': '일',
      'currentStatus': '현황',
      'trend': '트렌드',
      'monthlyTrend': '월별 지출 추이',
      'categoryComparison': '카테고리별 비교',
      'vsLastMonth': '전월 대비',
      'lastMonth': '지난달',
      'thisMonth': '이번달',
      'scanReceipt': '영수증 스캔',
      'ocrProcessing': '영수증 인식 중...',
      'ocrSuccess': '영수증 인식 완료',
      'ocrFailed': '영수증 인식 실패',
      'ocrAmountNotFound': '금액을 인식하지 못했습니다',
      'ocrDateNotFound': '날짜를 인식하지 못했습니다',
      'camera': '카메라',
      'gallery': '갤러리',
      'selectImageSource': '이미지 선택',

      // 위젯 설정
      'widgetSettings': '위젯 설정',
      'widgetUpdated': '위젯이 업데이트되었습니다',
      'smallWidget': 'Small 위젯',
      'smallWidgetDesc': '잔액만 간단히 표시 (2x1)',
      'mediumWidget': 'Medium 위젯',
      'mediumWidgetDesc': '지출과 잔액 표시 (3x2)',
      'largeWidget': 'Large 위젯',
      'largeWidgetDesc': '카테고리별 상세 (4x3)',
      'largeWidgetInfo': '전체 카테고리의 예산 현황을 자동으로 표시합니다',
      'selectSubBudgetOptional': '세부예산 선택 (선택사항)',
      'entireBudget': '전체 예산',
      'howToAddWidget': '위젯 추가 방법',
      'widgetAddGuide': '홈 화면을 길게 누르고 위젯 메뉴에서 "가계부"를 찾아 추가하세요.',
      'selectMonth': '월 선택',
      'moveUp': '위로 이동',
      'moveDown': '아래로 이동',

      // #27, #29: AI 분석 관련 추가
      'exportImage': '이미지로 내보내기',
      'analysisConfirmMessage': 'AI 분석을 요청하시겠습니까?',
      'remainingAnalyses': '오늘 남은 분석 횟수',
      'noRemainingAnalyses': '오늘 분석 횟수를 모두 사용했습니다. 내일 다시 시도해주세요.',
      'usageCheckFailed': '잔여 횟수 조회 실패. 분석을 진행합니다.',
    },
    'en': {
      'appTitle': 'Budget',
      'cancel': 'Cancel',
      'save': 'Save',
      'add': 'Add',
      'delete': 'Delete',
      'confirm': 'OK',
      'deleteConfirm': 'Confirm Delete',
      'edit': 'Edit',

      'budgetTab': 'Budget',
      'historyTab': 'History',
      'statsTab': 'Stats',
      'settingsTab': 'Settings',

      'budget': 'Budget',
      'used': 'Used',
      'remaining': 'Left',
      'ratio': 'Ratio',
      'total': 'Total',
      'difference': 'Diff',
      'changeRate': 'Change',
      'budgetName': 'Budget Name',
      'budgetNameHint': 'e.g., Food, Transport',
      'amount': 'Amount',
      'usedAmount': 'Spent',
      'addBudget': 'Add Budget',
      'editBudget': 'Edit Budget',
      'addBudgetPlease': 'Please add a budget',
      'applyMonthly': 'Apply Monthly',
      'applyMonthlyDesc': 'Auto-apply to future months',
      'numberOnlyError': 'Numbers only',

      'subBudget': 'Sub-budget',
      'subBudgetName': 'Sub-budget Name',
      'subBudgetNameHint': 'e.g., Lunch, Dinner',
      'addSubBudget': 'Add Sub-budget',
      'editSubBudget': 'Edit Sub-budget',
      'addSubBudgetPlease': 'Please add a sub-budget',
      'item': 'Item',

      'expense': 'Expense',
      'expenseHistory': 'Expenses',
      'addExpense': 'Add Expense',
      'editExpense': 'Edit Expense',
      'noExpense': 'No expenses',
      'memo': 'Description',
      'memoHint': 'e.g., Lunch kimbap',
      'date': 'Date',
      'subBudgetOptional': 'Sub-budget (Optional)',
      'notSelected': 'None',

      'budgetAllocation': 'Budget Allocation',
      'actualUsage': 'Actual Usage',
      'subBudgetAnalysis': 'Sub-budget Analysis',
      'selectBudget': 'Select a budget',
      'noBudget': 'No budget',
      'noSubBudget': 'No sub-budgets',
      'subBudgetUsage': 'Sub-budget Usage',
      'addBudgetFirst': 'Please add a budget first',

      'settings': 'Settings',
      'basicSettings': 'Basic Settings',
      'currency': 'Currency',
      'selectCurrency': 'Select Currency',
      'startDayOfWeek': 'Start Day',
      'selectStartDay': 'Select Start Day',
      'monthStartDay': 'Month Start',
      'selectMonthStartDay': 'Select Start Day',
      'monthStartDayDesc': 'Select payday or preferred date',
      'language': 'Language',
      'selectLanguage': 'Select Language',

      'notificationSettings': 'Notifications',
      'dailyReminder': 'Daily Reminder',
      'off': 'Off',
      'budgetAlert': 'Budget Alert',
      'budgetAlertThreshold': 'Alert Threshold',

      'displaySettings': 'Display/Theme',
      'darkMode': 'Dark Mode',
      'selectThemeMode': 'Select Theme',
      'systemSetting': 'System',
      'lightMode': 'Light',
      'darkModeOption': 'Dark',
      'fontSize': 'Font Size',
      'selectFontSize': 'Select Font Size',
      'fontSmall': 'Small',
      'fontNormal': 'Normal',
      'fontLarge': 'Large',
      'fontExtraLarge': 'Extra Large',
      'colorTheme': 'Color Theme',
      'selectColorTheme': 'Select Color',

      'others': 'Others',
      'appInfo': 'About',
      'version': 'Version',
      'help': 'Help',
      'appDesc': 'A simple budget app.',

      'helpBudgetTab': 'Budget Tab',
      'helpBudgetDesc': '• Add with + button\n• Tap for details\n• Long press to edit/delete',
      'helpSubBudget': 'Sub-budget',
      'helpSubBudgetDesc': '• Manage sub-items\n• Track per sub-budget',
      'helpStatsTab': 'Stats Tab',
      'helpStatsDesc': '• Pie charts\n• Tap for details',
      'helpTip': 'Tip',
      'helpTipDesc': '• Check "Apply Monthly" to auto-copy',

      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',

      'indigo': 'Indigo',
      'green': 'Green',
      'blue': 'Blue',
      'red': 'Red',
      'orange': 'Orange',
      'purple': 'Purple',
      'pink': 'Pink',
      'teal': 'Teal',

      'dataManagement': 'Data Management',
      'exportExcel': 'Export to Excel',
      'exportExcelDesc': 'Save current month data as Excel file',
      'exportSuccess': 'Export completed',
      'exportFailed': 'Export failed',
      'exporting': 'Exporting...',

      'aiAnalysis': 'AI Analysis',
      'geminiApiKey': 'Gemini API Key',
      'enterApiKey': 'Enter API key',
      'selectPeriod': 'Select Period',
      'requestAnalysis': 'Request Analysis',
      'analyzing': 'Analyzing...',
      'analysisResult': 'AI Analysis Result',
      'error': 'Error',
      'summary': 'Summary',
      'insights': 'Key Insights',
      'warnings': 'Warnings',
      'suggestions': 'Suggestions',
      'spendingPlan': 'Spending Plan',  // #13
      'spendingPattern': 'Spending Pattern',
      'mainCategory': 'Main Category',
      'spendingTrend': 'Spending Trend',
      'savingPotential': 'Saving Potential',
      'riskLevel': 'Risk Level',
      'trendIncreasing': 'Increasing',
      'trendDecreasing': 'Decreasing',
      'trendStable': 'Stable',
      'riskLow': 'Low',
      'riskMedium': 'Medium',
      'riskHigh': 'High',
      'duplicate': 'Duplicate',
      'duplicated': 'Duplicated',
      'cancelAnalysis': 'Cancel Analysis',
      'analysisInProgress': 'AI Analysis in Progress',
      'analysisCancelled': 'Analysis cancelled',
      'analysisComplete': 'AI Analysis Complete',
      'viewResult': 'View Result',
      'viewAnalysisResult': 'View Analysis Result',
      'analysisPeriod': 'Analysis Period',
      'analyzedAt': 'Analyzed At',
      'analysisHistory': 'Analysis History',
      'noAnalysisHistory': 'No analysis history',
      'clearHistoryConfirm': 'Delete all analysis history?',
      'clearAll': 'Clear All',
      'close': 'Close',
      'importExcel': 'Import from Excel',
      'importExcelDesc': 'Import data from Excel file',
      'importConfirm': 'Confirm Import',
      'importSummary': 'The following data will be imported:',
      'targetMonth': 'Target Month',
      'importing': 'Importing...',
      'importSuccess': 'Import completed',
      'importFailed': 'Import failed',
      'noDataToImport': 'No data to import',
      'items': 'items',
      'selectTone': 'Response Style',
      'responseTone': 'Response Style',
      'toneGentle': 'Gentle',
      'tonePraise': 'Encouraging',
      'toneFactual': 'Factual',
      'toneCoach': 'Coach',
      'toneHumorous': 'Humorous',
      'filter': 'Filter',
      'searchHint': 'Search memo, budget',
      'countUnit': ' items',
      'sortDateDesc': 'Newest',
      'sortDateAsc': 'Oldest',
      'sortAmountDesc': 'Highest',
      'sortAmountAsc': 'Lowest',
      'periodFilter': 'Period',
      'startDate': 'Start',
      'endDate': 'End',
      'budgetFilter': 'Budget',
      'subBudgetFilter': 'Sub-budget',
      'allBudgets': 'All Budgets',
      'allSubBudgets': 'All Sub-budgets',
      'resetFilter': 'Reset Filter',
      'noExpenseFound': 'No expenses found',
      'deleteExpenseConfirm': 'Delete this expense?',
      'recurringExpense': 'Recurring Expense',
      'recurringExpenseDesc': 'Manage automatic recurring expenses',
      'noRecurringExpense': 'No recurring expenses',
      'addRecurringExpense': 'Add Recurring Expense',
      'editRecurringExpense': 'Edit Recurring Expense',
      'deleteRecurringConfirm': 'Delete this recurring expense?',
      'repeatCycle': 'Repeat Cycle',
      'monthly': 'Monthly',
      'weekly': 'Weekly',
      'dayOfMonth': 'Day',
      'dayOfWeek': 'Day of Week',
      'dayUnit': '',
      'everyMonth': 'Every month',
      'everyWeek': 'Every',
      'monShort': 'Mon',
      'tueShort': 'Tue',
      'wedShort': 'Wed',
      'thuShort': 'Thu',
      'friShort': 'Fri',
      'satShort': 'Sat',
      'sunShort': 'Sun',
      'currentStatus': 'Current',
      'trend': 'Trend',
      'monthlyTrend': 'Monthly Spending Trend',
      'categoryComparison': 'Category Comparison',
      'vsLastMonth': 'vs Last Month',
      'lastMonth': 'Last Month',
      'thisMonth': 'This Month',
      'scanReceipt': 'Scan Receipt',
      'ocrProcessing': 'Processing receipt...',
      'ocrSuccess': 'Receipt recognized',
      'ocrFailed': 'Receipt recognition failed',
      'ocrAmountNotFound': 'Could not detect amount',
      'ocrDateNotFound': 'Could not detect date',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'selectImageSource': 'Select Image',

      // Widget Settings
      'widgetSettings': 'Widget Settings',
      'widgetUpdated': 'Widget updated',
      'smallWidget': 'Small Widget',
      'smallWidgetDesc': 'Shows balance only (2x1)',
      'mediumWidget': 'Medium Widget',
      'mediumWidgetDesc': 'Shows spending and balance (3x2)',
      'largeWidget': 'Large Widget',
      'largeWidgetDesc': 'Category details (4x3)',
      'largeWidgetInfo': 'Automatically displays budget status for all categories',
      'selectSubBudgetOptional': 'Select Sub-budget (Optional)',
      'entireBudget': 'Entire Budget',
      'howToAddWidget': 'How to Add Widget',
      'widgetAddGuide': 'Long press the home screen and find "Budget" in the widget menu to add.',
      'selectMonth': 'Select Month',
      'moveUp': 'Move Up',
      'moveDown': 'Move Down',

      // #27, #29: AI Analysis related
      'exportImage': 'Export as Image',
      'analysisConfirmMessage': 'Do you want to request AI analysis?',
      'remainingAnalyses': 'Remaining analyses today',
      'noRemainingAnalyses': 'You have used all analyses for today. Please try again tomorrow.',
      'usageCheckFailed': 'Failed to check remaining count. Proceeding with analysis.',
    },
    'ja': {
      'appTitle': '家計簿',
      'cancel': 'キャンセル',
      'save': '保存',
      'add': '追加',
      'delete': '削除',
      'confirm': '確認',
      'deleteConfirm': '削除確認',
      'edit': '編集',

      'budgetTab': '予算',
      'historyTab': '履歴',
      'statsTab': '統計',
      'settingsTab': '設定',

      'budget': '予算',
      'used': '使用',
      'remaining': '残り',
      'ratio': '比率',
      'total': '合計',
      'difference': '差額',
      'changeRate': '変動率',
      'budgetName': '予算名',
      'budgetNameHint': '例: 食費、交通費',
      'amount': '金額',
      'usedAmount': '使用金額',
      'addBudget': '予算追加',
      'editBudget': '予算編集',
      'addBudgetPlease': '予算を追加してください',
      'applyMonthly': '毎月適用',
      'applyMonthlyDesc': '以降の月に自動適用',
      'numberOnlyError': '数字のみ',

      'subBudget': 'サブ予算',
      'subBudgetName': 'サブ予算名',
      'subBudgetNameHint': '例: 昼食、夕食',
      'addSubBudget': 'サブ予算追加',
      'editSubBudget': 'サブ予算編集',
      'addSubBudgetPlease': 'サブ予算を追加',
      'item': '項目',

      'expense': '支出',
      'expenseHistory': '支出履歴',
      'addExpense': '支出追加',
      'editExpense': '支出編集',
      'noExpense': '支出なし',
      'memo': '内容',
      'memoHint': '例: 昼食キンパ',
      'date': '日付',
      'subBudgetOptional': 'サブ予算（任意）',
      'notSelected': 'なし',

      'budgetAllocation': '予算配分',
      'actualUsage': '実際の使用',
      'subBudgetAnalysis': 'サブ予算分析',
      'selectBudget': '予算を選択',
      'noBudget': '予算なし',
      'noSubBudget': 'サブ予算なし',
      'subBudgetUsage': 'サブ予算使用状況',
      'addBudgetFirst': '先に予算を追加',

      'settings': '設定',
      'basicSettings': '基本設定',
      'currency': '通貨',
      'selectCurrency': '通貨選択',
      'startDayOfWeek': '週の開始日',
      'selectStartDay': '開始日選択',
      'monthStartDay': '月の開始日',
      'selectMonthStartDay': '開始日選択',
      'monthStartDayDesc': '給料日や希望日を選択',
      'language': '言語',
      'selectLanguage': '言語選択',

      'notificationSettings': '通知設定',
      'dailyReminder': '毎日リマインダー',
      'off': 'オフ',
      'budgetAlert': '予算超過通知',
      'budgetAlertThreshold': '通知基準',

      'displaySettings': '画面/テーマ',
      'darkMode': 'ダークモード',
      'selectThemeMode': 'テーマ選択',
      'systemSetting': 'システム',
      'lightMode': 'ライト',
      'darkModeOption': 'ダーク',
      'fontSize': 'フォントサイズ',
      'selectFontSize': 'サイズ選択',
      'fontSmall': '小',
      'fontNormal': '中',
      'fontLarge': '大',
      'fontExtraLarge': '特大',
      'colorTheme': 'カラーテーマ',
      'selectColorTheme': 'カラー選択',

      'others': 'その他',
      'appInfo': 'アプリ情報',
      'version': 'バージョン',
      'help': 'ヘルプ',
      'appDesc': 'シンプルな家計簿アプリ',

      'helpBudgetTab': '予算タブ',
      'helpBudgetDesc': '• +で追加\n• タップで詳細\n• 長押しで編集/削除',
      'helpSubBudget': 'サブ予算',
      'helpSubBudgetDesc': '• サブ項目管理\n• 支出追跡',
      'helpStatsTab': '統計タブ',
      'helpStatsDesc': '• 円グラフ\n• タップで詳細',
      'helpTip': 'ヒント',
      'helpTipDesc': '• 「毎月適用」で自動コピー',

      'monday': '月曜日',
      'tuesday': '火曜日',
      'wednesday': '水曜日',
      'thursday': '木曜日',
      'friday': '金曜日',
      'saturday': '土曜日',
      'sunday': '日曜日',

      'indigo': 'インディゴ',
      'green': 'グリーン',
      'blue': 'ブルー',
      'red': 'レッド',
      'orange': 'オレンジ',
      'purple': 'パープル',
      'pink': 'ピンク',
      'teal': 'ティール',

      'dataManagement': 'データ管理',
      'exportExcel': 'Excelエクスポート',
      'exportExcelDesc': '今月のデータをExcelファイルで保存',
      'exportSuccess': 'エクスポート完了',
      'exportFailed': 'エクスポート失敗',
      'exporting': 'エクスポート中...',

      'aiAnalysis': 'AI分析',
      'geminiApiKey': 'Gemini APIキー',
      'enterApiKey': 'APIキーを入力',
      'selectPeriod': '分析期間選択',
      'requestAnalysis': '分析リクエスト',
      'analyzing': '分析中...',
      'analysisResult': 'AI分析結果',
      'error': 'エラー',
      'summary': 'サマリー',
      'insights': '重要な洞察',
      'warnings': '注意事項',
      'suggestions': '改善提案',
      'spendingPlan': '支出計画',  // #13
      'spendingPattern': '支出パターン',
      'mainCategory': '主要支出項目',
      'spendingTrend': '支出トレンド',
      'savingPotential': '節約可能額',
      'riskLevel': 'リスクレベル',
      'trendIncreasing': '増加傾向',
      'trendDecreasing': '減少傾向',
      'trendStable': '安定',
      'riskLow': '低い',
      'riskMedium': '普通',
      'riskHigh': '高い',
      'duplicate': '複製',
      'duplicated': '複製しました',
      'cancelAnalysis': '分析キャンセル',
      'analysisInProgress': 'AI分析進行中',
      'analysisCancelled': '分析がキャンセルされました',
      'analysisComplete': 'AI分析完了',
      'viewResult': '結果を見る',
      'viewAnalysisResult': '分析結果を確認',
      'analysisPeriod': '分析期間',
      'analyzedAt': '分析時点',
      'analysisHistory': '分析履歴',
      'noAnalysisHistory': '分析履歴がありません',
      'clearHistoryConfirm': 'すべての分析履歴を削除しますか？',
      'clearAll': '全て削除',
      'close': '閉じる',
      'importExcel': 'Excelからインポート',
      'importExcelDesc': 'Excelファイルからデータをインポート',
      'importConfirm': 'インポート確認',
      'importSummary': '以下のデータをインポートします:',
      'targetMonth': '対象月',
      'importing': 'インポート中...',
      'importSuccess': 'インポート完了',
      'importFailed': 'インポート失敗',
      'noDataToImport': 'インポートするデータがありません',
      'items': '件',
      'selectTone': '応答スタイル選択',
      'responseTone': '応答スタイル',
      'toneGentle': '穏やか',
      'tonePraise': '褒める',
      'toneFactual': 'ファクト重視',
      'toneCoach': 'コーチ',
      'toneHumorous': 'ユーモラス',
      'filter': 'フィルター',
      'searchHint': 'メモ、予算名で検索',
      'countUnit': '件',
      'sortDateDesc': '新しい順',
      'sortDateAsc': '古い順',
      'sortAmountDesc': '金額高い順',
      'sortAmountAsc': '金額低い順',
      'periodFilter': '期間',
      'startDate': '開始日',
      'endDate': '終了日',
      'budgetFilter': '予算',
      'subBudgetFilter': 'サブ予算',
      'allBudgets': '全ての予算',
      'allSubBudgets': '全てのサブ予算',
      'resetFilter': 'フィルターリセット',
      'noExpenseFound': '支出履歴がありません',
      'deleteExpenseConfirm': 'この支出を削除しますか？',
      'recurringExpense': '定期支出',
      'recurringExpenseDesc': '定期支出の自動登録を管理',
      'noRecurringExpense': '登録済みの定期支出がありません',
      'addRecurringExpense': '定期支出追加',
      'editRecurringExpense': '定期支出編集',
      'deleteRecurringConfirm': 'この定期支出を削除しますか？',
      'repeatCycle': '繰り返し周期',
      'monthly': '毎月',
      'weekly': '毎週',
      'dayOfMonth': '日付',
      'dayOfWeek': '曜日',
      'dayUnit': '日',
      'everyMonth': '毎月',
      'everyWeek': '毎週',
      'monShort': '月',
      'tueShort': '火',
      'wedShort': '水',
      'thuShort': '木',
      'friShort': '金',
      'satShort': '土',
      'sunShort': '日',
      'currentStatus': '現況',
      'trend': 'トレンド',
      'monthlyTrend': '月別支出推移',
      'categoryComparison': 'カテゴリー別比較',
      'vsLastMonth': '前月比',
      'lastMonth': '先月',
      'thisMonth': '今月',
      'scanReceipt': 'レシートスキャン',
      'ocrProcessing': 'レシート認識中...',
      'ocrSuccess': 'レシート認識完了',
      'ocrFailed': 'レシート認識失敗',
      'ocrAmountNotFound': '金額を認識できませんでした',
      'ocrDateNotFound': '日付を認識できませんでした',
      'camera': 'カメラ',
      'gallery': 'ギャラリー',
      'selectImageSource': '画像選択',

      // ウィジェット設定
      'widgetSettings': 'ウィジェット設定',
      'widgetUpdated': 'ウィジェットが更新されました',
      'smallWidget': 'Smallウィジェット',
      'smallWidgetDesc': '残高のみ表示 (2x1)',
      'mediumWidget': 'Mediumウィジェット',
      'mediumWidgetDesc': '支出と残高を表示 (3x2)',
      'largeWidget': 'Largeウィジェット',
      'largeWidgetDesc': 'カテゴリ別詳細 (4x3)',
      'largeWidgetInfo': '全カテゴリの予算状況を自動的に表示します',
      'selectSubBudgetOptional': '細目予算選択（任意）',
      'entireBudget': '予算全体',
      'howToAddWidget': 'ウィジェットの追加方法',
      'widgetAddGuide': 'ホーム画面を長押しして、ウィジェットメニューから「家計簿」を探して追加してください。',
      'selectMonth': '月選択',
      'moveUp': '上に移動',
      'moveDown': '下に移動',

      // #27, #29: AI分析関連
      'exportImage': '画像としてエクスポート',
      'analysisConfirmMessage': 'AI分析をリクエストしますか？',
      'remainingAnalyses': '今日の残り分析回数',
      'noRemainingAnalyses': '今日の分析回数をすべて使用しました。明日再度お試しください。',
      'usageCheckFailed': '残り回数の確認に失敗しました。分析を進めます。',
    },
  };

  final String language;
  AppLocalizations(this.language);

  String tr(String key) {
    return _localizedValues[language]?[key] ?? _localizedValues['ko']![key] ?? key;
  }

  String formatCurrency(int amount, String currencySymbol) {
    final formatted = NumberFormat('#,###', 'ko_KR').format(amount);
    if (currencySymbol == '₩') {
      return '$formatted원';
    }
    if (currencySymbol == '¥') {
      return '$formatted$currencySymbol';
    }
    return '$currencySymbol$formatted';
  }
}

extension LocalizationExtension on BuildContext {
  AppLocalizations get loc {
    final settings = Provider.of<SettingsProvider>(this, listen: false);
    return AppLocalizations(settings.language);
  }

  String get currency {
    final settings = Provider.of<SettingsProvider>(this, listen: false);
    return settings.currency == '₩' ? '원' : settings.currency;
  }

  String formatCurrency(int amount) {
    final settings = Provider.of<SettingsProvider>(this, listen: false);
    return AppLocalizations(settings.language).formatCurrency(amount, settings.currency);
  }
}
